services:
  snowmirror:
    container_name: snowmirror
    image: mikevandenberge/snowmirror:latest
    ports:
      - "443:443"
    volumes:
      - "./snowMirror.properties:/opt/snowmirror/snowMirror.properties"
      - "./logs:/opt/snowmirror/logs"
