name: ci

on:
  push:
    branches:
      - '**' #every branch
  pull_request:
    branches:
      - '**' #every branch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Build
        run: |
          echo "Start CI build"
          echo "VERSION=$(head -n 1 version.txt)" >> $GITHUB_ENV
          envsubst < Dockerfile.template > Dockerfile
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multibuilder
          docker buildx use multibuilder
          docker buildx build --platform linux/amd64,linux/arm64 -t mikevandenberge/snowmirror:${VERSION}-ci .
