name: Release Dev Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
  release:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Start CI build"
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multibuilder
          docker buildx use multibuilder
          docker buildx build --build-arg BUILD_VERSION_ARG=${VERSION} --platform linux/amd64 -t mikevdberge/snowmirror:${VERSION}-dev -t mikevdberge/snowmirror:latest-dev . --push