name: Release Dev Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true


jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # ✅ minimal required
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # ✅ minimal required    
    needs: setup
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}
          persist-credentials: false          
      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Start CI build"
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multibuilder
          docker buildx use multibuilder
          docker buildx build --build-arg BUILD_VERSION_ARG=${VERSION} --build-arg SNOWMIRROR_VERSION=${VERSION} --platform linux/amd64 -t mikevandenberge/snowmirror:${VERSION}-dev -t mikevandenberge/snowmirror:latest-dev . --push
